<?php

use yii\db\Schema;
use yii\db\Migration;

class m150222_093419_create_currency_table extends Migration
{
    public function up()
    {
        $this->createTable('currency', [
            'code' => 'CHAR(3) NOT NULL',
            0 => 'PRIMARY KEY (`code`)',
            'name' => 'VARCHAR(64) NOT NULL',
        ]);

        $this->batchInsert('currency', [
            'code', 'name'
        ],[
            ['ADP', 'Andorran Peseta'],
            ['AED', 'United Arab Emirates Dirham'],
            ['AFA', 'Afghanistan Afghani'],
            ['ALL', 'Albanian Lek'],
            ['AMD', 'Armenian Dram'],
            ['ANG', 'Netherlands Antillian Guilder'],
            ['AOK', 'Angolan Kwanza'],
            ['ARS', 'Argentine Peso'],
            ['AUD', 'Australian Dollar'],
            ['AWG', 'Aruban Florin'],
            ['BBD', 'Barbados Dollar'],
            ['BDT', 'Bangladeshi Taka'],
            ['BGN', 'Bulgarian Lev'],
            ['BHD', 'Bahraini Dinar'],
            ['BIF', 'Burundi Franc'],
            ['BMD', 'Bermudian Dollar'],
            ['BND', 'Brunei Dollar'],
            ['BOB', 'Bolivian Boliviano'],
            ['BRL', 'Brazilian Real'],
            ['BSD', 'Bahamian Dollar'],
            ['BTN', 'Bhutan Ngultrum'],
            ['BUK', 'Burma Kyat'],
            ['BWP', 'Botswanian Pula'],
            ['BZD', 'Belize Dollar'],
            ['CAD', 'Canadian Dollar'],
            ['CHF', 'Swiss Franc'],
            ['CLF', 'Chilean Unidades de Fomento'],
            ['CLP', 'Chilean Peso'],
            ['CNY', 'Yuan (Chinese) Renminbi'],
            ['COP', 'Colombian Peso'],
            ['CRC', 'Costa Rican Colon'],
            ['CUP', 'Cuban Peso'],
            ['CVE', 'Cape Verde Escudo'],
            ['CYP', 'Cyprus Pound'],
            ['CZK', 'Czech Republic Koruna'],
            ['DKK', 'Danish Krone'],
            ['DOP', 'Dominican Peso'],
            ['DZD', 'Algerian Dinar'],
            ['ECS', 'Ecuador Sucre'],
            ['EEK', 'Estonian Kroon (EEK)'],
            ['EGP', 'Egyptian Pound'],
            ['ETB', 'Ethiopian Birr'],
            ['EUR', 'Euro'],
            ['FJD', 'Fiji Dollar'],
            ['FKP', 'Falkland Islands Pound'],
            ['GBP', 'British Pound'],
            ['GHC', 'Ghanaian Cedi'],
            ['GIP', 'Gibraltar Pound'],
            ['GMD', 'Gambian Dalasi'],
            ['GNF', 'Guinea Franc'],
            ['GTQ', 'Guatemalan Quetzal'],
            ['GWP', 'Guinea-Bissau Peso'],
            ['GYD', 'Guyanan Dollar'],
            ['HKD', 'Hong Kong Dollar'],
            ['HNL', 'Honduran Lempira'],
            ['HTG', 'Haitian Gourde'],
            ['HUF', 'Hungarian Forint'],
            ['IDR', 'Indonesian Rupiah'],
            ['IEP', 'Irish Punt'],
            ['ILS', 'Israeli Shekel'],
            ['INR', 'Indian Rupee'],
            ['IQD', 'Iraqi Dinar'],
            ['IRR', 'Iranian Rial'],
            ['JMD', 'Jamaican Dollar'],
            ['JOD', 'Jordanian Dinar'],
            ['JPY', 'Japanese Yen'],
            ['KES', 'Kenyan Schilling'],
            ['KHR', 'Kampuchean (Cambodian) Riel'],
            ['KMF', 'Comoros Franc'],
            ['KPW', 'North Korean Won'],
            ['KRW', 'South Korean Won'],
            ['KWD', 'Kuwaiti Dinar'],
            ['KYD', 'Cayman Islands Dollar'],
            ['LAK', 'Lao Kip'],
            ['LBP', 'Lebanese Pound'],
            ['LKR', 'Sri Lanka Rupee'],
            ['LRD', 'Liberian Dollar'],
            ['LSL', 'Lesotho Loti'],
            ['LYD', 'Libyan Dinar'],
            ['MAD', 'Moroccan Dirham'],
            ['MGF', 'Malagasy Franc'],
            ['MNT', 'Mongolian Tugrik'],
            ['MOP', 'Macau Pataca'],
            ['MRO', 'Mauritanian Ouguiya'],
            ['MTL', 'Maltese Lira'],
            ['MUR', 'Mauritius Rupee'],
            ['MVR', 'Maldive Rufiyaa'],
            ['MWK', 'Malawi Kwacha'],
            ['MXP', 'Mexican Peso'],
            ['MYR', 'Malaysian Ringgit'],
            ['MZM', 'Mozambique Metical'],
            ['NAD', 'Namibian Dollar'],
            ['NGN', 'Nigerian Naira'],
            ['NIO', 'Nicaraguan Cordoba'],
            ['NOK', 'Norwegian Kroner'],
            ['NPR', 'Nepalese Rupee'],
            ['NZD', 'New Zealand Dollar'],
            ['OMR', 'Omani Rial'],
            ['PAB', 'Panamanian Balboa'],
            ['PEN', 'Peruvian Nuevo Sol'],
            ['PGK', 'Papua New Guinea Kina'],
            ['PHP', 'Philippine Peso'],
            ['PKR', 'Pakistan Rupee'],
            ['PLN', 'Polish Zloty'],
            ['PYG', 'Paraguay Guarani'],
            ['QAR', 'Qatari Rial'],
            ['RON', 'Romanian Leu'],
            ['RUB', 'Russian Ruble'],
            ['RWF', 'Rwanda Franc'],
            ['SAR', 'Saudi Arabian Riyal'],
            ['SBD', 'Solomon Islands Dollar'],
            ['SCR', 'Seychelles Rupee'],
            ['SDP', 'Sudanese Pound'],
            ['SEK', 'Swedish Krona'],
            ['SGD', 'Singapore Dollar'],
            ['SHP', 'St. Helena Pound'],
            ['SKK', 'Slovak Koruna'],
            ['SLL', 'Sierra Leone Leone'],
            ['SOS', 'Somali Schilling'],
            ['SRG', 'Suriname Guilder'],
            ['STD', 'Sao Tome and Principe Dobra'],
            ['SVC', 'El Salvador Colon'],
            ['SYP', 'Syrian Potmd'],
            ['SZL', 'Swaziland Lilangeni'],
            ['THB', 'Thai Baht'],
            ['TND', 'Tunisian Dinar'],
            ['TOP', 'Tongan Paanga'],
            ['TPE', 'East Timor Escudo'],
            ['TRY', 'Turkish Lira'],
            ['TTD', 'Trinidad and Tobago Dollar'],
            ['TWD', 'Taiwan Dollar'],
            ['TZS', 'Tanzanian Schilling'],
            ['UGX', 'Uganda Shilling'],
            ['USD', 'US Dollar'],
            ['UYU', 'Uruguayan Peso'],
            ['VEF', 'Venezualan Bolivar'],
            ['VND', 'Vietnamese Dong'],
            ['VUV', 'Vanuatu Vatu'],
            ['WST', 'Samoan Tala'],
            ['XAF', 'CommunautÃ© FinanciÃ¨re Africaine BEAC, Francs'],
            ['XAG', 'Silver, Ounces'],
            ['XAU', 'Gold, Ounces'],
            ['XCD', 'East Caribbean Dollar'],
            ['XDR', 'International Monetary Fund (IMF) Special Drawing Rights'],
            ['XOF', 'CommunautÃ© FinanciÃ¨re Africaine BCEAO - Francs'],
            ['XPD', 'Palladium Ounces'],
            ['XPF', 'Comptoirs FranÃ§ais du Pacifique Francs'],
            ['XPT', 'Platinum, Ounces'],
            ['YDD', 'Democratic Yemeni Dinar'],
            ['YER', 'Yemeni Rial'],
            ['YUD', 'New Yugoslavia Dinar'],
            ['ZAR', 'South African Rand'],
            ['ZMK', 'Zambian Kwacha'],
            ['ZRZ', 'Zaire Zaire'],
            ['ZWD', 'Zimbabwe Dollar'],
        ]);
    }

    public function down()
    {
        $this->dropTable('currency');
        return false;
    }
}
